#!/bin/sh /etc/rc.common

START=12
STOP=99

start() {	
	config_load mymodule_config
	config_foreach getOptionValue BeaconConfig
}

stop() {
	echo "My Init Program stop" > /etc/showMyInit
}

getOptionValue() {
	local interval ifenable repeat string
	config_get interval "$1" interval
	config_get ifenable "$1" ifenable
	config_get repeat "$1" repeat
	config_get string "$1" interrupt_string
	echo "$interval" > /etc/config/myconfig/beacon_interval
	echo "$ifenable" > /etc/config/myconfig/ifenable
	echo "$repeat" > /etc/config/myconfig/repeat
	echo "$string" > /etc/config/myconfig/interrupt_string	
}
